config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("prueba/", include("core.erp.urls")),
]

core/erp/urls.py
from django.urls import path

from .views import myfirstview, mysecondview

app_name = "vistas"
urlpatterns = [
    path("categorias/", myfirstview, name="categorias"),
    path("productos/", mysecondview, name="productos"),
]

core/erp/models.py
from django.db import models
from datetime import datetime
from core.erp.choices import gender_choices


class Type(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nombre", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "tipos"
        verbose_name = "Tipo"
        verbose_name_plural = "Tipos"
        ordering = ["id"]


class Employee(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nombre")
    dni = models.CharField(max_length=10, verbose_name="DNI")
    date_joined = models.DateField(default=datetime.now, verbose_name="Fecha_Registro")
    date_creation = models.DateField(auto_now=True)
    date_updated = models.DateField(auto_now_add=True)
    type = models.ForeignKey(Type, related_name="emples", on_delete=models.CASCADE)
    age = models.PositiveIntegerField(default=0)
    salary = models.DecimalField(default=0.0, max_digits=9, decimal_places=2)
    state = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to="avatar/%Y/%m/%d", null=True, blank=True)
    cvitae = models.FileField(upload_to="avatar/%Y/%m/%d", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "empleados"
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ["id"]


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nombre", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "categories"
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["id"]


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nombre", unique=True)
    cate = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product/%Y/%m/%d", null=True, blank=True)
    pvp = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "products"
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["id"]


class Client(models.Model):
    names = models.CharField(max_length=150, verbose_name="Nombres")
    surnames = models.CharField(max_length=150, verbose_name="Apellidos")
    dni = models.CharField(max_length=10, unique=True, verbose_name="Dni")
    birthday = models.DateField(
        default=datetime.now, verbose_name="Fecha de nacimiento"
    )
    address = models.CharField(
        max_length=150, null=True, blank=True, verbose_name="Dirección"
    )
    sexo = models.CharField(
        max_length=10, choices=gender_choices, default="male", verbose_name="Sexo"
    )

    def __str__(self):
        return self.names

    class Meta:
        db_table = "customers"
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ["id"]


class Sale(models.Model):
    cli = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_joined = models.DateField(default=datetime.now)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    iva = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.cli.names

    class Meta:
        db_table = "sales"
        verbose_name = "Venta"
        verbose_name_plural = "Ventas"
        ordering = ["id"]


class DetSale(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    prod = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    cant = models.IntegerField(default=0)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.prod.name

    class Meta:
        db_table = "detsales"
        verbose_name = "Detalle de Venta"
        verbose_name_plural = "Detalle de Ventas"
        ordering = ["id"]

core/erp/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import Category, Product


def myfirstview(request):
    data = {"title": "Categorías", "items": Category.objects.all()}
    return render(request, "home.html", data)


def mysecondview(request):
    data = {"title": "Productos", "items": Product.objects.all()}
    return render(request, "home.html", data)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>General</title>
    <link
      rel="stylesheet"
      href="{% static 'lib/bootstrap-5.2.1-dist/css/bootstrap.min.css' %}"
    />
    <script src="{% static 'lib/jquery-3.5.1/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap-5.2.1-dist/js/popper.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap-5.2.1-dist/js/bootstrap.min.js' %}"></script>
  </head>
  <body class="container mt-5">
    <h1>Listado General</h1>
    <img src="{% static 'img/user_icon.png' %}" width="100px" alt="user_icon" />
    {% block content %} {% endblock content %}
    <hr />
    <!-- Probando buttons -->
    <button type="button" class="btn btn-primary">Primary</button>
    <button type="button" class="btn btn-secondary">Secondary</button>
    <button type="button" class="btn btn-success">Success</button>
    <button type="button" class="btn btn-danger">Danger</button>
    <button type="button" class="btn btn-warning">Warning</button>
    <button type="button" class="btn btn-info">Info</button>
    <button type="button" class="btn btn-light">Light</button>
    <button type="button" class="btn btn-dark">Dark</button>
    <button type="button" class="btn btn-link">Link</button>

    <!-- Probando un accordeon -->
    <hr />
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            Accordion Item #1
          </button>
        </h2>
        <div
          id="collapseOne"
          class="accordion-collapse collapse show"
          aria-labelledby="headingOne"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <strong>This is the first item's accordion body.</strong> It is
            shown by default, until the collapse plugin adds the appropriate
            classes that we use to style each element. These classes control the
            overall appearance, as well as the showing and hiding via CSS
            transitions. You can modify any of this with custom CSS or
            overriding our default variables. It's also worth noting that just
            about any HTML can go within the <code>.accordion-body</code>,
            though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseTwo"
            aria-expanded="false"
            aria-controls="collapseTwo"
          >
            Accordion Item #2
          </button>
        </h2>
        <div
          id="collapseTwo"
          class="accordion-collapse collapse"
          aria-labelledby="headingTwo"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <strong>This is the second item's accordion body.</strong> It is
            hidden by default, until the collapse plugin adds the appropriate
            classes that we use to style each element. These classes control the
            overall appearance, as well as the showing and hiding via CSS
            transitions. You can modify any of this with custom CSS or
            overriding our default variables. It's also worth noting that just
            about any HTML can go within the <code>.accordion-body</code>,
            though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseThree"
            aria-expanded="false"
            aria-controls="collapseThree"
          >
            Accordion Item #3
          </button>
        </h2>
        <div
          id="collapseThree"
          class="accordion-collapse collapse"
          aria-labelledby="headingThree"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is
            hidden by default, until the collapse plugin adds the appropriate
            classes that we use to style each element. These classes control the
            overall appearance, as well as the showing and hiding via CSS
            transitions. You can modify any of this with custom CSS or
            overriding our default variables. It's also worth noting that just
            about any HTML can go within the <code>.accordion-body</code>,
            though the transition does limit overflow.
          </div>
        </div>
      </div>
    </div>
    <!-- Final accordeon -->
  </body>
</html>

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">Anything you want</div>
  <!-- Default to the left -->
  <strong
    >Copyright &copy; 2014-2021
    <a href="https://adminlte.io">AdminLTE.io</a>.</strong
  >
  All rights reserved.
</footer>

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
  <div class="container">
    <a href="../../index3.html" class="navbar-brand">
      <img
        src="{% static 'lib/adminlte-3.2.0/img/AdminLTELogo.png' %}"
        alt="AdminLTE Logo"
        class="brand-image img-circle elevation-3"
        style="opacity: 0.8"
      />
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <button
      class="navbar-toggler order-1"
      type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a
            id="dropdownSubMenu1"
            href="#"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            class="nav-link dropdown-toggle"
            >Dropdown</a
          >
          <ul
            aria-labelledby="dropdownSubMenu1"
            class="dropdown-menu border-0 shadow"
          >
            <li><a href="#" class="dropdown-item">Some action </a></li>
            <li>
              <a href="#" class="dropdown-item">Some other action</a>
            </li>

            <li class="dropdown-divider"></li>

            <!-- Level two dropdown-->
            <li class="dropdown-submenu dropdown-hover">
              <a
                id="dropdownSubMenu2"
                href="#"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                class="dropdown-item dropdown-toggle"
                >Hover for action</a
              >
              <ul
                aria-labelledby="dropdownSubMenu2"
                class="dropdown-menu border-0 shadow"
              >
                <li>
                  <a tabindex="-1" href="#" class="dropdown-item">level 2</a>
                </li>

                <!-- Level three dropdown-->
                <li class="dropdown-submenu">
                  <a
                    id="dropdownSubMenu3"
                    href="#"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                    class="dropdown-item dropdown-toggle"
                    >level 2</a
                  >
                  <ul
                    aria-labelledby="dropdownSubMenu3"
                    class="dropdown-menu border-0 shadow"
                  >
                    <li>
                      <a href="#" class="dropdown-item">3rd level</a>
                    </li>
                    <li>
                      <a href="#" class="dropdown-item">3rd level</a>
                    </li>
                  </ul>
                </li>
                <!-- End Level three -->

                <li><a href="#" class="dropdown-item">level 2</a></li>
                <li><a href="#" class="dropdown-item">level 2</a></li>
              </ul>
            </li>
            <!-- End Level two -->
          </ul>
        </li>
      </ul>

      <!-- SEARCH FORM -->
      <form class="form-inline ml-0 ml-md-3">
        <div class="input-group input-group-sm">
          <input
            class="form-control form-control-navbar"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>

    <!-- Right navbar links -->
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img
                src="{% static 'lib/adminlte-3.2.0/img/user1-128x128.jpg' %}"
                alt="User Avatar"
                class="img-size-50 mr-3 img-circle"
              />
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"
                    ><i class="fas fa-star"></i
                  ></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted">
                  <i class="far fa-clock mr-1"></i> 4 Hours Ago
                </p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img
                src="{% static 'lib/adminlte-3.2.0/img/user8-128x128.jpg' %}"
                alt="User Avatar"
                class="img-size-50 img-circle mr-3"
              />
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"
                    ><i class="fas fa-star"></i
                  ></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted">
                  <i class="far fa-clock mr-1"></i> 4 Hours Ago
                </p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img
                src="{% static 'lib/adminlte-3.2.0/img/user3-128x128.jpg' %}"
                alt="User Avatar"
                class="img-size-50 img-circle mr-3"
              />
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"
                    ><i class="fas fa-star"></i
                  ></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted">
                  <i class="far fa-clock mr-1"></i> 4 Hours Ago
                </p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer"
            >See All Notifications</a
          >
        </div>
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          data-widget="control-sidebar"
          data-slide="true"
          href="#"
          role="button"
        >
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </div>
</nav>
<!-- /.navbar -->

templates/home.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AdminLTE 3 | Top Navigation</title>

    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome Icons -->
    <link
      rel="stylesheet"
      href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link
      rel="stylesheet"
      href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}"
    />
  </head>
  <body class="hold-transition layout-top-nav">
    <div class="wrapper">
      {% include "header.html" %}

      <div class="content-wrapper">{% block content %} {% endblock %}</div>

      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>

      {% include "footer.html" %}
    </div>

    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/adminlte-3.2.0/js/demo.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends "home.html" %} {% block content %}
<h1>Hola Mundo</h1>
{% endblock %}

templates/index0.html
{% extends "base.html" %} {% block content %}
<button type="button" class="btn btn-primary">
  <a href="{% url 'vistas:categorias' %}" class="text-white">Categorias</a>
</button>
<button type="button" class="btn btn-success">
  <a href="{% url 'vistas:productos' %}" class="text-white">Productos</a>
</button>

<h3 class="mt-3">Listado de {{ title | upper }}</h3>
{% if items %}
<ul>
  {% for item in items %}
  <li>{{item.id}} - {{item.name}}</li>
  {% endfor %}
</ul>
{% else %}
<h4>No existen datos</h4>
{% endif %} {% endblock content %}